#! /bin/sh

if [ "$1" == "-h" -o "$1" == "-help" ]
then
  echo 'usage: WebDiff repo_url sha_commit_1 sha_commit_2'
  echo 'Tool to generate visual comparisons between git commits for a website'
  exit 0
fi

# cleanup after exit and/or on error
function on_exit {
    echo "\nDone!"
}

function on_error {
    echo "An error occured."
}

# we do not want the script to silently fail
trap on_error ERR
trap on_exit EXIT


if [ ! -d www/project ]; then
    echo "Cloning repo... \n"
    git clone $1 www/project
else
    echo "Project folder exists. Removing previous repo \n"
    rm -rf www/project
    echo "Cloning repo... \n"
    git clone $1 www/project
fi

cd www/project
echo "Pulling at sha... $2" 
git checkout $2

echo "Taking pics.. \n"
python ../../../webkit2png/webkit2png -F -o ../pics/$2 http://0.0.0.0:8000/project

echo "Pulling at sha... $3" 
git checkout $3

echo "Taking pics.. \n"
python ../../../webkit2png/webkit2png -F -o ../pics/$3 http://0.0.0.0:8000/project

echo "Putting into webpage"
cd ../

sed -i "" '/<div class="pic_container">/ a\
    <h4>Repo: '$1'</h4><h4>Commit: '$2'</h4><img src="pics/'$2'-full.png" ><h4>Commit: '$3'</h4><img src="pics/'$3'-full.png" >' index.html
    